version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wp:/var/www/html/
    restart: always
    depends_on:
      - wordpress
    networks:
      - docker_network
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp:/var/www/html/
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
    restart: always
    depends_on:
      - mariadb
    networks:
      - docker_network
    ports:
      - 9000

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    networks:
      - docker_network
    ports:
      - 3306

volumes:
  wp:
  db:

networks:
  docker_network: