version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wp:/var/www/wordpress
    ports:
      - "443:443"
    restart: always

volumes:
  wp:
    driver: local
    driver_opts:
    # maybe type none is default ,can be ommited
      type: none
      device: /home/${USER}/data/wordpress
      o: bind