version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wp:/var/www/html/
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    networks:
      - docker_network

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp:/var/www/html/
    restart: always
    networks:
      - docker_network
    ports:
      - 9000

volumes:
  wp:
    driver: local
    driver_opts:
    # maybe type none is default, can be ommited
      type: none
      device: /home/preed/data/wordpress
      o: bind

networks:
  docker_network: